import Navbar from '@/components/navbar';
import PaymentOrder from '@/components/payment-order';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "PotatoPos",
    description: "Generated by create next app",
};


const PosLayout = ({
    children
}: {
    children: React.ReactNode
}) => {
    return (
        <div className='flex h-full w-full'>
            <main className='bg-slate-100 w-full md:w-[calc(100%-400px)] xl:w-[calc(100%-500px)]'>
                <Navbar />
                {children}
            </main>
            <aside className='bg-white fixed right-0 h-full text-black hidden md:block md:w-[400px] xl:w-[500px]'>
                <PaymentOrder />
            </aside>
        </div>
    )
}

export default PosLayout